// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ApacheService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::functions;

class ApacheServiceHandler : virtual public ApacheServiceIf {
 public:
  ApacheServiceHandler() {
    // Your initialization goes here
  }

  int64_t add(const AddRequest& request) {
    // Your implementation goes here
    printf("add\n");
  }

  void printrandom() {
    // Your implementation goes here
    printf("printrandom\n");
  }

  int64_t fibonacci(const int64_t input) {
    // Your implementation goes here
    printf("fibonacci\n");
  }

  void onlydigits(std::string& _return, const std::string& input) {
    // Your implementation goes here
    printf("onlydigits\n");
  }

  void getuser(User& _return, const int32_t id) {
    // Your implementation goes here
    printf("getuser\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<ApacheServiceHandler> handler(new ApacheServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new ApacheServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

